In [16]:
import numpy as np
arr = np.array([10,20,15,30,45,10,90,100])
print('Entire array is')
print(arr)
print('first element is ', arr[0]) 
print('last element is ', arr[6])
print('sum of element of array is ', sum(arr))
print('mean is ', arr.mean())
print('Standard Deviation is ', arr.std())
print('Maximum vaue is ', arr.max())
print('Minimum value is ', arr.min())
print('product is ', arr.prod())
print('variance is ', arr.var())
print('Median is ', np.median(arr))
print('Sorted array is ', np.sort(arr))
print('the Reversed array is ', np.flip(arr))
print('sort in descending order is ', np.flip(np.sort(arr)))
print('All index of value 10 is: ' , np.where(arr == 10)[0]) 
print('first index of value 30 is: ' , np.where(arr == 30)[0][0])


Entire array is
[ 10  20  15  30  45  10  90 100]
first element is  10
last element is  90
sum of element of array is  320
mean is  40.0
Standard Deviation is  33.63406011768428
Maximum vaue is  100
Minimum value is  10
product is  -572220160
variance is  1131.25
Median is  25.0
Sorted array is  [ 10  10  15  20  30  45  90 100]
the Reversed array is  [100  90  10  45  30  15  20  10]
sort in descending order is  [100  90  45  30  20  15  10  10]
All index of value 10 is:  [0 5]
first index of value 30 is:  3


In [18]:
import numpy as np
arr2D = np.array([[10,20,15,30,45],
                 [78,20,30,56,83],
                 [16,17,18,19,20]])
print('the 2D array is ')
print(arr2D)
print('Dimension is' , np.ndim(arr2D))
print('Shape is ' , np.shape(arr2D))


the 2D array is 
[[10 20 15 30 45]
 [78 20 30 56 83]
 [16 17 18 19 20]]
Dimension is 2
Shape is  (3, 5)


In [22]:
import numpy as np
arr2D = np.array([[10,20,15,30,45],
                 [78,20,30,56,83],
                 [16,17,18,19,20],
                 [18,20,33,23,45]])
print('print all elements')
print(arr2D[::])
print('\nprints element of second row (ind is 1) and third column(ind is 1)')
print(arr2D[1:2,2:3])
print('\nprints row with index 1 (second row)')
print(arr2D[1:2,:])
print('\nprints column with index 2 (third column)')
print(arr2D[:,2:3])
print('\nprints row with index 1 & 2 and column 1 & 2')
print(arr2D[1:3,1:3])

print all elements
[[10 20 15 30 45]
 [78 20 30 56 83]
 [16 17 18 19 20]
 [18 20 33 23 45]]

prints element of second row (ind is 1) and third column(ind is 1)
[[30]]

prints row with index 1 (second row)
[[78 20 30 56 83]]

prints column with index 2 (third column)
[[15]
 [30]
 [18]
 [33]]

prints row with index 1 & 2 and column 1 & 2
[[20 30]
 [17 18]]
